ServerRoot /usr
ServerName pivault
PidFile /run/apache2/httpd.pid
Listen 80
Listen 443
LoadModule authz_core_module lib/apache2/modules/mod_authz_core.so
LoadModule authz_host_module lib/apache2/modules/mod_authz_host.so
LoadModule unixd_module lib/apache2/modules/mod_unixd.so
LoadModule log_config_module lib/apache2/modules/mod_log_config.so
LoadModule mime_module lib/apache2/modules/mod_mime.so
LoadModule dir_module lib/apache2/modules/mod_dir.so
LoadModule alias_module lib/apache2/modules/mod_alias.so
LoadModule ssl_module lib/apache2/modules/mod_ssl.so
LoadModule socache_shmcb_module lib/apache2/modules/mod_socache_shmcb.so
LoadModule php_module lib/apache2/modules/libphp.so
User www-data
Group www-data
ServerTokens Prod
ServerSignature Off
ErrorLog /var/log/apache2/error_log
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog /var/log/apache2/access_log common
TypesConfig /etc/apache2/mime.types
DocumentRoot /usr/share/apache2/default-site/htdocs
<Directory />
    AllowOverride None
    Require all denied
</Directory>
<Directory /usr/share/apache2/default-site/htdocs>
    Options -Indexes
    Require all granted
    DirectoryIndex index.php index.html
</Directory>
<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
<FilesMatch "^\.">
    Require all denied
</FilesMatch>
php_value session.save_path /run/php-sessions
php_value openssl.cafile /etc/ssl/certs/ca-certificates.crt
Include /etc/apache2/extra/dokuwiki.conf
SSLProtocol -all +TLSv1.2 +TLSv1.3
SSLSessionCache shmcb:/run/apache2/ssl_scache(512000)
<VirtualHost *:80>
    <Location />
        Redirect permanent "https://%{HTTP_HOST}%{REQUEST_URI}"
    </Location>
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile /etc/apache2/tls/server.crt.pem
    SSLCertificateKeyFile /etc/apache2/tls/server.key.pem
    SSLCACertificateFile /etc/apache2/tls/client-ca.crt.pem
    SSLVerifyClient require
    SSLVerifyDepth 1
</VirtualHost>
