[taky]
hostname = zero
node_id = TAKY
bind_ip = 192.168.50.1
public_ip = 192.168.50.1

[cot_server]
port = 8089
mon_ip = 127.0.0.1
mon_port = 8087

[ssl]
enabled = true
client_cert_required = false
ca = /etc/taky/ssl/ca.crt
cert = /etc/taky/ssl/server.crt
key = /etc/taky/ssl/server.key
