LVGL_DEMO_SITE = ${BR2_EXTERNAL}/local/lvgl/lvgl-demo
LVGL_DEMO_SITE_METHOD = local
LVGL_DEMO_INSTALL_STAGING = YES
LVGL_DEMO_INSTALL_TARGET = YES
LVGL_DEMO_AUTORECONF = YES
LVGL_DEMO_LICENSE_FILES = COPYING
$(eval $(cmake-package))
