LVGL_COM_VERSION = 5b3e24b2685084a95cb9bad78da61a3e84d79d85
LVGL_COM_SITE = https://codeberg.org/resiliencetheatre/lvgl-com.git
LVGL_COM_SITE_METHOD = git
LVGL_COM_DEPENDENCIES += libpng zlib
LVGL_COM_INSTALL_STAGING = YES
LVGL_COM_INSTALL_TARGET = YES
LVGL_COM_AUTORECONF = YES
LVGL_COM_LICENSE_FILES = COPYING
$(eval $(cmake-package))
