LVGL_COM_VERSION = 72449b2769bbb77f7f4da5369bc51b68e1b69787
LVGL_COM_SITE = https://codeberg.org/resiliencetheatre/lvgl-com.git
LVGL_COM_SITE_METHOD = git
LVGL_COM_DEPENDENCIES += libpng zlib
LVGL_COM_INSTALL_STAGING = YES
LVGL_COM_INSTALL_TARGET = YES
LVGL_COM_AUTORECONF = YES
LVGL_COM_LICENSE_FILES = COPYING
$(eval $(cmake-package))
