LVGL_COM_VERSION = b7412ad61a8a79f1f9226b25c2d9cd978b5e018f
LVGL_COM_SITE = https://codeberg.org/resiliencetheatre/lvgl-com.git
LVGL_COM_SITE_METHOD = git
LVGL_COM_DEPENDENCIES += libpng zlib
LVGL_COM_INSTALL_STAGING = YES
LVGL_COM_INSTALL_TARGET = YES
LVGL_COM_AUTORECONF = YES
LVGL_COM_LICENSE_FILES = COPYING
$(eval $(cmake-package))
