protocols = imap
listen = *

mail_location = mbox:~/mail:INBOX=/var/mail/%u

ssl = no
disable_plaintext_auth = no

auth_mechanisms = plain login
auth_username_format = %Ln

passdb {
  driver = passwd-file
  args = /etc/dovecot/users
}

userdb {
  driver = passwd
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

service auth {
  unix_listener /var/run/dovecot/auth-exim {
    mode = 0660
    user = exim
    group = mail
  }
}
