[Unit]
# Start only after your USB target has fired
Requires=usb-plug.target
After=usb-plug.target
RequiresMountsFor=/mnt/usb
BindsTo=mnt-usb.mount
After=mnt-usb.mount
Wants=mnt-usb.automount
After=mnt-usb.automount
After=udp2raw.service
