Alias /dokuwiki /usr/share/dokuwiki
<Directory /usr/share/dokuwiki>
    Options -Indexes
    AllowOverride None
    Require all granted
    DirectoryIndex doku.php
    <FilesMatch "\.php$">
        SetHandler application/x-httpd-php
    </FilesMatch>
    <FilesMatch "^([._]ht|README$|VERSION$|COPYING$|SECURITY\.md$)">
        Require all denied
    </FilesMatch>
</Directory>
<DirectoryMatch "^/usr/share/dokuwiki/(conf|data|bin|inc|vendor)(/|$)">
    Require all denied
</DirectoryMatch>
