LVGL_APP_SITE = ${BR2_EXTERNAL}/local/lvgl/lvgl-app
LVGL_APP_SITE_METHOD = local
LVGL_APP_INSTALL_STAGING = YES
LVGL_APP_INSTALL_TARGET = YES
LVGL_APP_AUTORECONF = YES
LVGL_APP_LICENSE_FILES = COPYING
$(eval $(cmake-package))
